---
title: "Supplements"
output: html_document
---

```{r, message = FALSE, warning = FALSE}

library(RColorBrewer)

setwd("~/Desktop/DESKTOP/induce_library/figs/")

induce_combo <- subset(induce_exp, grepl("COMBO", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal", "Min_35", "Min_10", "Proximal"), sep = "-", remove = F)

induce_distal <- subset(induce_exp, grepl("DISTAL", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal", "Offset", "Min_35", "Core", "Min_10"), sep = "-", remove = F)

induce_distal$Min_35 <- with(induce_distal, reorder(Min_35, ratio, median))
induce_distal$Min_10 <- with(induce_distal, reorder(Min_10, ratio, median))
induce_distal$Core <- with(induce_distal, reorder(Core, ratio, median))
induce_distal$Distal <- with(induce_distal, reorder(Distal, ratio, median))

```

```{r}
combo_scram_exp <- filter(induce_combo, Proximal == 'lacOscram', Distal == 'lacOscram', Min_10 == 'minus10cons', Min_35 == 'minus35cons')$normalized_RNA_exp_UnInduced_12

combo_comp <- induce_combo %>%
  filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Distal == 'lacOscram') %>%
  dplyr::mutate(norm_exp = normalized_RNA_exp_UnInduced_12/combo_scram_exp) %>%
  select(Library, Proximal, norm_exp) %>%
  filter(Proximal == 'lacO1' | Proximal == 'lacO2' | Proximal == 'lacO3' | Proximal == 'lacOsym' | Proximal == 'lacOscram')

distal_scram_exp <- filter(induce_distal, Core == 'lacOscram', Distal == 'lacOscram', Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>% select(Offset, normalized_RNA_exp_UnInduced_12)

distal_comp <- left_join(induce_distal, distal_scram_exp, by = 'Offset') %>%
  filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  dplyr::mutate(norm_exp = normalized_RNA_exp_UnInduced_12.x/normalized_RNA_exp_UnInduced_12.y) %>%
  select(Library, Proximal = Core, Distal, Offset, norm_exp) %>%
  unique(.)
distal_comp <- distal_comp[!is.na(distal_comp$norm_exp),]

pal5 <- brewer.pal(n=5, name ='RdYlBu')
distal_comp$Distal <- factor(distal_comp$Distal, levels = c('lacOscram','lacO3','lacO2','lacO1','lacOsym'))

ggplot(distal_comp, aes(y = log2(norm_exp), fill = Distal, x = Proximal)) + 
  geom_bar(position = "dodge", stat = 'identity') + 
  #geom_boxplot(outlier.shape = NA) +
  #geom_jitter(aes(color = Distal)) +
  scale_x_discrete(limits = c('lacOscram', 'lacO3', 'lacO2', 'lacO1', 'lacOsym')) +
  labs(x = 'Core', y = 'log2(Normalized uninduced expression)') + 
#  scale_fill_manual(values = pal5) +
  scale_fill_viridis(discrete = TRUE, name = 'Distal operator') +
  facet_wrap(~Offset) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  labs(x = 'Core operator', y = expression('log'[2]~'(Normalized uninduced expression)'))
ggsave('Supp2.png', width = 20, height = 10)
```

```{r}
# Supplement 1: Osym vs. O1

filler <- c("midnightblue", "orange") 

t1 <- induce_combo %>%
  filter(Distal == 'lacOsym', (Proximal == 'lacO1' | Proximal == 'lacOsym'), Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>% 
  ggplot(aes(x = Proximal, y = normalized_RNA_exp_Induced_12)) + geom_bar(stat = 'identity', fill = filler, color = 'black') + ylab("Induced Expression")

t2 <- induce_combo %>%
  filter(Distal == 'lacOsym', Proximal == 'lacO1' | Proximal == 'lacOsym', Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  ggplot(aes(x = Proximal, y = normalized_RNA_exp_UnInduced_12)) + geom_bar(stat = 'identity', fill = filler, color = 'black') + ylab("Basal Expression")

plot_grid(t1, t2) 
ggsave('Supp1.png', height = 6, width = 8)
```
